// NES system — compiled dispatch loop
//
// Instead of interpreting each 6502 instruction, this dispatches to
// pre-compiled Rust blocks generated by build.rs. Falls back to a
// single-instruction interpreter for addresses not covered.

use crate::bus::Bus;
use crate::cartridge::Cartridge;
use crate::cpu_state::CpuState;
use crate::interpreter;

// Include the generated compiled blocks
include!(concat!(env!("OUT_DIR"), "/compiled_blocks.rs"));

pub struct Nes {
    pub cpu: CpuState,
    pub bus: Bus,
    ppu_debt: u32,
    pub audio_enabled: bool,
    pub ppu_rendering: bool,
}

impl Nes {
    /// Create NES with embedded ROM (no file needed at runtime).
    pub fn embedded() -> Self {
        let cart = Cartridge::from_embedded(&EMBEDDED_PRG, EMBEDDED_PRG_BANKS);
        Self::new(cart)
    }

    pub fn new(cart: Cartridge) -> Self {
        let mut nes = Nes {
            cpu: CpuState::new(),
            bus: Bus::new(cart),
            ppu_debt: 0,
            audio_enabled: true,
            ppu_rendering: true,
        };
        nes.cpu.reset(&mut nes.bus);
        nes
    }

    #[inline(never)]
    pub fn run_frame(&mut self) -> u64 {
        let target = self.bus.ppu.frame_count + 1;
        loop {
            self.step();
            // Check after step since PPU is ticked in tick_hw
            if self.bus.ppu.frame_count >= target { break; }
        }
        self.bus.ppu.frame_count
    }

    #[inline(always)]
    fn step(&mut self) {
        // Handle DMA
        if self.bus.dma_pending {
            let cycles = self.bus.do_dma();
            self.cpu.stall += cycles;
        }

        // Handle stall
        if self.cpu.stall > 0 {
            let s = self.cpu.stall;
            self.cpu.stall = 0;
            self.cpu.cycles += s as u64;
            self.tick_hw(s);
            return;
        }

        // Check interrupts
        if self.cpu.nmi_pending {
            self.cpu.nmi_pending = false;
            self.cpu.nmi(&mut self.bus);
            self.tick_hw(7);
            return;
        }
        if self.cpu.irq_pending && !self.cpu.i {
            self.cpu.irq(&mut self.bus);
            self.tick_hw(7);
            return;
        }

        let start = self.cpu.cycles;

        // Try compiled dispatch first
        let bank = self.bus.cart.bank_select;
        let pc = self.cpu.pc;
        if !dispatch(bank, pc, &mut self.cpu, &mut self.bus) {
            // Fallback: interpret one instruction
            interpreter::step(&mut self.cpu, &mut self.bus);
        }

        let elapsed = (self.cpu.cycles - start) as u32;
        self.tick_hw(elapsed);
    }

    #[inline(always)]
    fn tick_hw(&mut self, cpu_cycles: u32) {
        // PPU: batched scanlines
        self.ppu_debt += cpu_cycles * 3;
        if self.ppu_debt >= 341 {
            loop {
                self.ppu_debt -= 341;
                let cart = &self.bus.cart;
                if self.ppu_rendering {
                    if self.bus.ppu.finish_scanline(cart) {
                        self.cpu.nmi_pending = true;
                    }
                } else {
                    if self.bus.ppu.finish_scanline_minimal(cart) {
                        self.cpu.nmi_pending = true;
                    }
                }
                if self.ppu_debt < 341 { break; }
            }
        }

        // APU: batched clock
        if self.audio_enabled {
            self.bus.apu.clock_batch(cpu_cycles);

            // DMC read + frame IRQ
            if self.bus.apu.dmc_read_pending.is_some() | self.bus.apu.frame_irq {
                if let Some(addr) = self.bus.apu.dmc_read_pending.take() {
                    let byte = self.bus.read(addr);
                    self.bus.apu.dmc_fill_buffer(byte);
                }
                if self.bus.apu.frame_irq {
                    self.cpu.irq_pending = true;
                }
            }
        } else {
            // Minimal APU: only track frame counter for IRQ generation
            self.bus.apu.clock_batch_minimal(cpu_cycles);
            if self.bus.apu.frame_irq {
                self.cpu.irq_pending = true;
            }
        }
    }

    pub fn set_button(&mut self, player: usize, button: u8, pressed: bool) {
        if player > 1 { return; }
        if pressed {
            self.bus.controller[player] |= 1 << button;
        } else {
            self.bus.controller[player] &= !(1 << button);
        }
    }

    pub fn framebuffer(&self) -> &[u32] {
        &self.bus.ppu.framebuffer
    }
}
